<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Reject;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Reject::insert([
            [
                'name' => 'Spam',
                'description'=> 'The content is repetitive and does not provide value. \n The message appears to be automated or generated by a bot.'
            ],
            [
                'name' => 'Irrelevant Content',
                'description'=> 'The message does not relate to the brand or product. \n Content is not appropriate for the platform.'
            ],
            [
                'name' => 'Offensive Language',
                'description'=> 'The message contains offensive or inappropriate language. \n It includes hate speech, discrimination, or personal attacks.'
            ],
            [
                'name' => 'Inappropriate Media',
                'description'=> 'The post contains inappropriate images, videos, or other media. \n The media violates community standards or guidelines.'
            ],
            [
                'name' => 'False Information',
                'description'=> 'The content includes misleading or false information. \n It spreads misinformation or fake news.'
            ],
            [
                'name' => 'Violates Brand Guidelines',
                'description'=> 'The post does not align with the brand\'s values or guidelines. \n It includes content that goes against the brand image.'
            ],
            [
                'name' => 'Duplicate Content',
                'description'=> 'The same content has been posted multiple times. \n The user is repeating the same message across different channels.'
            ],
            [
                'name' => 'Off-Topic',
                'description'=> 'The content is not related to the ongoing conversation or the brand. \n It veers off-topic and does not contribute to the discussion.'
            ],
            [
                'name' => 'Privacy Concerns',
                'description'=> 'The post includes sensitive information that should not be shared publicly. \n The user\'s privacy may be compromised.'
            ],
            [
                'name' => 'Legal Issues',
                'description'=> 'The content violates legal regulations or copyright laws. \n It requires legal attention and should not be handled by regular support.'
            ],
            [
                'name' => 'Unverified Account',
                'description'=> 'The user account is unverified, and the message may not be legitimate. \n It could be a potential security risk.'
            ],
            [
                'name' => 'Language Barrier',
                'description'=> 'The message is in a language that the support team does not understand. \n It needs to be directed to a team or service that can handle that language.'
            ],
        ]);
    }
}
